# Generated by Django 4.2.17 on 2024-12-21 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examp1', '0002_flowers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flowers',
            options={'managed': True},
        ),
        migrations.AlterField(
            model_name='flowers',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterModelTable(
            name='flowers',
            table='Flowers',
        ),
    ]
